deptrac:
  paths:
    - ../../fixtures
    - ../../src
    - ../../tests

  layers:
    - name: Functions
      collectors:
        - type: class
          value: \\MartinGeorgiev\\Doctrine\\ORM\\AST\\Functions\\.*
    - name: Types
      collectors:
        - type: class
          value: \\MartinGeorgiev\\Doctrine\\DBAL\\Types\\.*
    - name: Utils
      collectors:
        - type: class
          value: \\MartinGeorgiev\\Utils\\.*
    - name: Fixtures
      collectors:
        - type: class
          value: \\Fixtures\\MartinGeorgiev\\.*
    - name: Integration Tests
      collectors:
        - type: class
          value: \\Tests\\Integration\\MartinGeorgiev\\.*
    - name: Unit Tests
      collectors:
        - type: class
          value: \\Tests\\Unit\\MartinGeorgiev\\.*

  ruleset:
    Functions:
      - Utils
    Types:
      - Utils
    Utils: ~
    Integration Tests:
      - Fixtures
      - Functions
      - Types
    Unit Tests:
      - Fixtures
      - Functions
      - Types
      - Utils
