deptrac:
  paths:
    - ../../src
    - ../../tests

  layers:
    - name: Functions
      collectors:
        - type: class
          value: \\MartinGeorgiev\\Doctrine\\ORM\\AST\\Functions\\.*
    - name: Types
      collectors:
        - type: class
          value: \\MartinGeorgiev\\Doctrine\\DBAL\\Types\\.*
    - name: Utils
      collectors:
        - type: class
          value: \\MartinGeorgiev\\Utils\\.*
    - name: Tests
      collectors:
        - type: class
          value: \\Tests\\MartinGeorgiev\\.*

  ruleset:
    Functions:
      - Utils
    Types:
      - Utils
    Utils: ~
    Tests:
      - Functions
      - Types
      - Utils
